# Generated by Django 4.1.4 on 2023-02-22 15:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Статья')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='URL')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('thumbsup', models.IntegerField(default='0', verbose_name='Нравится')),
                ('thumbsdown', models.IntegerField(default='0', verbose_name='Не нравится')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Comments_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('text', models.TextField(max_length=700, verbose_name='Текст комментария')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость комментария')),
            ],
            options={
                'verbose_name': 'Комментарий статьи',
                'verbose_name_plural': 'Комментарии статей',
                'ordering': ['-status', '-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Thematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Тематика')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тематику',
                'verbose_name_plural': 'Тематики',
            },
        ),
        migrations.CreateModel(
            name='Votes_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=True)),
                ('article', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='articleid', to='articles.article')),
            ],
        ),
    ]
