# Generated by Django 4.1.4 on 2023-02-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes_article',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userarticleid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments_article',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_article', to='articles.article', verbose_name='Название Статьи'),
        ),
        migrations.AddField(
            model_name='comments_article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_article_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AddField(
            model_name='article',
            name='thematic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.thematic', verbose_name='Тематика'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbs',
            field=models.ManyToManyField(blank=True, default=None, related_name='thumbs_article', to=settings.AUTH_USER_MODEL, verbose_name='Голосовали'),
        ),
    ]
