# Generated by Django 4.1.4 on 2023-02-22 15:05

import albums.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Альбом')),
                ('cover', models.ImageField(upload_to=albums.models.album_directory_path, verbose_name='Обложка')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('thumbsup', models.IntegerField(default='0', verbose_name='Нравится')),
                ('thumbsdown', models.IntegerField(default='0', verbose_name='Не нравится')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Comments_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('text', models.TextField(max_length=700, verbose_name='Текст комментария')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость комментария')),
            ],
            options={
                'verbose_name': 'Комментарий альбома',
                'verbose_name_plural': 'Комментарии альбомов',
                'ordering': ['-status', '-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.CharField(max_length=60, unique=True, verbose_name='Название изображения')),
                ('image', models.ImageField(upload_to=albums.models.album_image_directory_path, verbose_name='Изображение')),
                ('comment_image', models.CharField(max_length=40, verbose_name='Комментарий изображения')),
                ('title_image_description', models.CharField(max_length=60, unique=True, verbose_name='Название изображения с пояснениями')),
                ('image_description', models.ImageField(upload_to=albums.models.album_image_directory_path, verbose_name='Изображение с пояснениями')),
                ('comment_image_description', models.CharField(max_length=40, verbose_name='Комментарий изображения с пояснениями')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Organ_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Система органов')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Систему органов',
                'verbose_name_plural': 'Системы органов',
            },
        ),
        migrations.CreateModel(
            name='Votes_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=True)),
                ('album', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='albumid', to='albums.album')),
            ],
        ),
    ]
