# Generated by Django 4.1.4 on 2023-02-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='votes_album',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='useralbumid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumimages', to='albums.album', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='comments_album',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_album', to='albums.album', verbose_name='Название Альбома'),
        ),
        migrations.AddField(
            model_name='comments_album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_album_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AddField(
            model_name='album',
            name='organ_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.organ_system', verbose_name='Система органов'),
        ),
        migrations.AddField(
            model_name='album',
            name='thumbs',
            field=models.ManyToManyField(blank=True, default=None, related_name='thumbs_album', to=settings.AUTH_USER_MODEL, verbose_name='Голосовали'),
        ),
    ]
