# Generated by Django 4.1.4 on 2023-02-16 03:51

import albums.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to=albums.models.album_directory_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='comments_album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_album_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=albums.models.album_image_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_description',
            field=models.ImageField(upload_to=albums.models.album_image_directory_path, verbose_name='Изображение с пояснениями'),
        ),
    ]
