# Generated by Django 4.1.4 on 2023-02-16 03:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatar/default/default_avatar.jpeg', upload_to=users.models.user_directory_path, verbose_name='Аватар'),
        ),
    ]
