# Generated by Django 4.1.4 on 2023-01-21 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(101)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Не указано'), ('М', 'Мужчина'), ('Ж', 'Женщина')], default='-', max_length=1, verbose_name='Пол'),
        ),
    ]
