# Generated by Django 4.1.4 on 2022-12-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_age_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/static/users/avatar/default/default_avatar.jpeg', upload_to='users/avatar/', verbose_name='Аватар'),
        ),
    ]
