# Generated by Django 4.1.4 on 2023-01-16 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_age_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(110), django.core.validators.MinValueValidator(18)], verbose_name='Возраст'),
        ),
    ]
