# Generated by Django 4.1.4 on 2023-02-22 15:05

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Comments_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('text', models.TextField(max_length=700, verbose_name='Текст комментария')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость комментария')),
            ],
            options={
                'verbose_name': 'Комментарий постa',
                'verbose_name_plural': 'Комментарии постов',
                'ordering': ['-status', '-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Пост')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to=blog.models.post_directory_path, verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Текст')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('thumbsup', models.IntegerField(default='0', verbose_name='Нравится')),
                ('thumbsdown', models.IntegerField(default='0', verbose_name='Не нравится')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Votes_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=True)),
                ('post', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='postid', to='blog.post')),
            ],
        ),
    ]
