# Generated by Django 4.1.4 on 2023-01-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Название'),
        ),
    ]
