# Generated by Django 4.1.4 on 2023-02-22 15:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Приветствие')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание приветсвия')),
            ],
            options={
                'verbose_name': 'Приветствие',
                'verbose_name_plural': 'Приветствие',
            },
        ),
    ]
