# Generated by Django 4.1.4 on 2023-01-21 22:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_commentspost_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='commentspost',
            managers=[
                ('x', django.db.models.manager.Manager()),
            ],
        ),
    ]
