# Generated by Django 4.1.4 on 2023-01-16 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_post_text_userslikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(through='blog.UsersLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
