# Generated by Django 4.1.4 on 2023-01-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_commentspost_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='commentspost',
            managers=[
            ],
        ),
    ]
