# Generated by Django 4.1.4 on 2023-01-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_commentspost_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentspost',
            options={'ordering': ['-status', '-create_date'], 'verbose_name': 'Комментарий постa', 'verbose_name_plural': 'Комментарии постов'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='commentspost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_post', to='blog.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='commentspost',
            name='text',
            field=models.TextField(max_length=700, verbose_name='Текст комментария'),
        ),
    ]
